spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guns?useunicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.cgx.springdemo.model
  mapper-locations: classpath:com.cgx.springdemo/**/mapping/*.xml